=== mgenware/qing/userland/config/schema/core.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "core-config-schema",
  "type": "object",
  "definitions": {
    "dev_config": {
      "type": "object",
      "properties": {
        "reload_views_on_refresh": { "type": "boolean" },
        "panic_on_unexpected_html_errors": { "type": "boolean" },
        "panic_on_unexpected_json_errors": { "type": "boolean" },
        "no_dev_mail": { "type": "boolean" },
        "turbo_web": {
          "type": "object",
          "properties": {
            "dir": { "type": "string" },
            "url": { "type": "string" }
          }
        },
        "mailbox": {
          "type": "object",
          "properties": {
            "url": { "type": "string" }
          }
        }
      }
    },
    "site_config": {
      "type": "object",
      "properties": {
        "url": { "type": "string" },
        "name": { "type": "string" },
        "post_permission": { "type": "number" },
        "langs": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["url", "name", "langs"]
    },
    "logging_config": {
      "type": "object",
      "properties": {
        "dir": { "type": "string" }
      },
      "required": ["dir"]
    },
    "security_config": {
      "type": "object",
      "properties": {
        "hashing": { "$ref": "#/definitions/hashing_config" }
      },
      "required": ["hashing"]
    },
    "http_config": {
      "type": "object",
      "properties": {
        "port": {
          "type": "number",
          "minimum": 0
        },
        "log_404_error": { "type": "boolean" },
        "static": {
          "type": "object",
          "properties": {
            "url": { "type": "string" },
            "dir": { "type": "string" }
          },
          "required": ["url", "dir"]
        }
      },
      "required": ["static"]
    },
    "templates_config": {
      "type": "object",
      "properties": {
        "dir": { "type": "string" }
      },
      "required": ["dir"]
    },
    "db_config": {
      "type": "object",
      "properties": {
        "user": { "type": "string" },
        "pwd": { "type": "string" },
        "database": { "type": "string" },
        "host": { "type": "string" },
        "port": {
          "type": "number",
          "minimum": 0
        },
        "params": { "type": "string" }
      },
      "required": ["user", "pwd", "database", "host", "port", "params"]
    },
    "res_server_config": {
      "type": "object",
      "properties": {
        "url": { "type": "string" },
        "dir": { "type": "string" }
      },
      "required": ["url", "dir"]
    },
    "extern_config": {
      "type": "object",
      "properties": {
        "redis": {
          "type": "object",
          "properties": {
            "port": {
              "type": "number",
              "minimum": 1
            },
            "logging": { "type": "boolean" }
          },
          "required": ["port"]
        },
        "img_proxy": {
          "type": "object",
          "properties": {
            "port": {
              "type": "number",
              "minimum": 1
            }
          },
          "required": ["port"]
        }
      },
      "required": ["redis", "img_proxy"]
    },
    "forums_config": {
      "type": "object",
      "properties": {
        "enabled": { "type": "boolean" }
      }
    },
    "z_test_config": {
      "type": "object",
      "properties": {
        "a": { "type": "number" },
        "b": { "type": "number" },
        "c": { "type": "number" }
      }
    }
  },
  "properties": {
    "extends": { "type": "string" },
    "dev": { "$ref": "#/definitions/dev_config" },
    "logging": { "$ref": "#/definitions/logging_config" },
    "http": { "$ref": "#/definitions/http_config" },
    "templates": { "$ref": "#/definitions/templates_config" },
    "db": { "$ref": "#/definitions/db_config" },
    "res_server": { "$ref": "#/definitions/res_server_config" },
    "extern": { "$ref": "#/definitions/extern_config" },
    "forums": { "$ref": "#/definitions/forums_config" },
    "site": { "$ref": "#/definitions/site_config" },
    "security": { "$ref": "#/definitions/security_config" },
    "z_test": { "$ref": "#/definitions/z_test_config" }
  },
  "required": ["logging", "http", "templates", "db", "res_server", "extern", "site", "security"]
}

=== mgenware/qing/userland/config/dev/core/base.json
{
  "http": {
    "port": 8000,
    "static": {
      "url": "/static",
      "dir": "/qing/static"
    },
    "log_404_error": true
  },
  "templates": {
    "dir": "/qing/templates"
  },
  "logging": {
    "dir": "/qing_data/log/dev"
  },
  "db": {
    "user": "qing_dev",
    "pwd": "qing_dev_pwd",
    "host": "db",
    "port": 3306,
    "database": "qing_dev",
    "params": "?parseTime=true&collation=utf8mb4_unicode_ci&clientFoundRows=true"
  },
  "res_server": {
    "url": "/res",
    "dir": "/qing_data/res_server"
  },
  "dev": {
    "reload_views_on_refresh": true,
    "mailbox": {
      "dir": "/qing_data/mailbox"
    },
    "turbo_web": {
      "dir": "/qing/web",
      "url": "/static-turbo"
    }
  },
  "security": {
    "hashing": {
      "memory": 65536,
      "iterations": 3,
      "parallelism": 16,
      "salt_length": 32,
      "key_length": 2
    }
  },
  "site": {
    "url": "https://__QING__",
    "name": "__QING__",
    "langs": ["en", "zh-Hans"]
  },
  "extern": {
    "redis": {
      "port": 6379,
      "logging": true
    },
    "img_proxy": {
      "port": 9000
    }
  }
}
